#!/usr/bin/env python
"""
parse_val_format.py - parse the .val file format generated by tbl2asn. It contains errors and warnings
"""
import sys
import re
import pandas as pd

val_path = '/Users/david/work/mayo_lab_sequence_submission/tillie/additional_oc_sequences_for_submission.A2.val'
out_gff_path = '/Users/david/work/mayo_lab_sequence_submission/tillie/additional_oc_sequences_for_submission.gff'
gff = pd.read_csv(out_gff_path, sep="\t", header = None, comment='#', index_col=0)

full_pat = re.compile(r"(\w+):(.+)FEATURE:(.+)")
label_pat = re.compile(r"\[(.*?)\]")
id_pat = re.compile(r".+lcl|(\w+): raw, .+")
print("orig_id", "id", "level", "message", "data", sep="\t")
with open(val_path) as val_fh:
    for line in val_fh:
        match = re.search(full_pat, line)
        if match is None:
            print(">>>> Failed to match line with pattern", file=sys.stderr)
            print(f">>>> {line}", file=sys.stderr)
            continue
        level = match[1]
        message = match[2].strip()
        data = match[3].strip()

        # print(f"{level}:",f"\tMSG: {message}",f"\tDATA: {data}",sep="\n")
        labels = re.findall(label_pat, data)
        id_match = re.search(id_pat, labels[1])
        
        if id_match is None:
            print("Couldn't figure out id from ${labels[1]}", file=sys.stderr)
            id = None
        else:
            id = id_match[1]
        # print(f"\tID: {id}")
        # print('', *labels,sep="\n\t\t")
        orig_id = None
        if id in gff.index:
            orig_id = gff.loc[id][10]
        print(orig_id, id, level, message, data, sep="\t")

        pass